version: "3.3"

services:
  traefik:
    image: traefik:v1.7
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      #- "--entrypoints=Name:http Address::80 "
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=CORREO@DOMINIO.net"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=DOMINIO.net"
      - "--docker.watch"
      - "--logLevel=DEBUG"
      - "--accessLog"
    ports:
      - "80:80"
      - "443:443"
      - "8383:8080"
      - "587:587"
      - "465:465"

    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - /directorio-base/traefik/traefik.toml:/traefik.toml:ro # master file to save all the config for traefik
      - /directorio-base/traefik:/etc/traefik/acme # autogenerate reading the config file (traefik.toml)
      - /dirctorio-base/tmp:/tmp
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.port=8080"
        #- "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.stickiness=true"
        #- "traefik.backend.loadbalancer.sticky=true" #Deprecated configuration
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:proxy.DOMINIO.net"
        - "traefik.frontend.auth.basic:admin:$apr1$G/ZU8lWP$lHzIC8pjGrx8JsrWkzqgO."
networks:
  web: # docker network to work apps backend swarm mode
    driver: overlay
